var annotated_dup =
[
    [ "antlr4", null, [
      [ "QueryErrorHandler", "classantlr4_1_1QueryErrorHandler.html", "classantlr4_1_1QueryErrorHandler" ]
    ] ],
    [ "cli", null, [
      [ "BuildCommand", "classcli_1_1BuildCommand.html", "classcli_1_1BuildCommand" ],
      [ "Command", "classcli_1_1Command.html", "classcli_1_1Command" ],
      [ "Commands", "classcli_1_1Commands.html", "classcli_1_1Commands" ],
      [ "ProxyCommand", "classcli_1_1ProxyCommand.html", "classcli_1_1ProxyCommand" ],
      [ "RegexCommand", "classcli_1_1RegexCommand.html", "classcli_1_1RegexCommand" ],
      [ "ServeCommand", "classcli_1_1ServeCommand.html", "classcli_1_1ServeCommand" ],
      [ "ShellCommand", "classcli_1_1ShellCommand.html", "classcli_1_1ShellCommand" ],
      [ "StressCommand", "classcli_1_1StressCommand.html", "classcli_1_1StressCommand" ]
    ] ],
    [ "netspeak", null, [
      [ "bighashmap", null, [
        [ "BigHashMap", "classnetspeak_1_1bighashmap_1_1BigHashMap.html", "classnetspeak_1_1bighashmap_1_1BigHashMap" ],
        [ "Builder", "classnetspeak_1_1bighashmap_1_1Builder.html", "classnetspeak_1_1bighashmap_1_1Builder" ],
        [ "CmphMap", "classnetspeak_1_1bighashmap_1_1CmphMap.html", "classnetspeak_1_1bighashmap_1_1CmphMap" ],
        [ "ExternalMap", "classnetspeak_1_1bighashmap_1_1ExternalMap.html", "classnetspeak_1_1bighashmap_1_1ExternalMap" ],
        [ "InternalMap", "classnetspeak_1_1bighashmap_1_1InternalMap.html", "classnetspeak_1_1bighashmap_1_1InternalMap" ]
      ] ],
      [ "invertedindex", null, [
        [ "ByteBuffer", "classnetspeak_1_1invertedindex_1_1ByteBuffer.html", "classnetspeak_1_1invertedindex_1_1ByteBuffer" ],
        [ "Configuration", "classnetspeak_1_1invertedindex_1_1Configuration.html", "classnetspeak_1_1invertedindex_1_1Configuration" ],
        [ "Indexer", "classnetspeak_1_1invertedindex_1_1Indexer.html", "classnetspeak_1_1invertedindex_1_1Indexer" ],
        [ "IndexStrategy", "classnetspeak_1_1invertedindex_1_1IndexStrategy.html", "classnetspeak_1_1invertedindex_1_1IndexStrategy" ],
        [ "InvertedFileReader", "classnetspeak_1_1invertedindex_1_1InvertedFileReader.html", "classnetspeak_1_1invertedindex_1_1InvertedFileReader" ],
        [ "InvertedFileWriter", "classnetspeak_1_1invertedindex_1_1InvertedFileWriter.html", "classnetspeak_1_1invertedindex_1_1InvertedFileWriter" ],
        [ "page_type", "structnetspeak_1_1invertedindex_1_1page__type.html", "structnetspeak_1_1invertedindex_1_1page__type" ],
        [ "swap_type", "structnetspeak_1_1invertedindex_1_1swap__type.html", "structnetspeak_1_1invertedindex_1_1swap__type" ],
        [ "iterator_type", "structnetspeak_1_1invertedindex_1_1iterator__type.html", "structnetspeak_1_1invertedindex_1_1iterator__type" ],
        [ "constant_size_iter", "structnetspeak_1_1invertedindex_1_1constant__size__iter.html", "structnetspeak_1_1invertedindex_1_1constant__size__iter" ],
        [ "variable_size_iter", "structnetspeak_1_1invertedindex_1_1variable__size__iter.html", "structnetspeak_1_1invertedindex_1_1variable__size__iter" ],
        [ "ManagedIndexer", "classnetspeak_1_1invertedindex_1_1ManagedIndexer.html", "classnetspeak_1_1invertedindex_1_1ManagedIndexer" ],
        [ "Postlist", "classnetspeak_1_1invertedindex_1_1Postlist.html", "classnetspeak_1_1invertedindex_1_1Postlist" ],
        [ "PostlistBuilder", "classnetspeak_1_1invertedindex_1_1PostlistBuilder.html", "classnetspeak_1_1invertedindex_1_1PostlistBuilder" ],
        [ "PostlistReader", "classnetspeak_1_1invertedindex_1_1PostlistReader.html", "classnetspeak_1_1invertedindex_1_1PostlistReader" ],
        [ "PostlistSorter", "classnetspeak_1_1invertedindex_1_1PostlistSorter.html", "classnetspeak_1_1invertedindex_1_1PostlistSorter" ],
        [ "Properties", "structnetspeak_1_1invertedindex_1_1Properties.html", "structnetspeak_1_1invertedindex_1_1Properties" ],
        [ "RawIndexer", "classnetspeak_1_1invertedindex_1_1RawIndexer.html", "classnetspeak_1_1invertedindex_1_1RawIndexer" ],
        [ "Head", "structnetspeak_1_1invertedindex_1_1Head.html", "structnetspeak_1_1invertedindex_1_1Head" ],
        [ "RawPostlist", "classnetspeak_1_1invertedindex_1_1RawPostlist.html", "classnetspeak_1_1invertedindex_1_1RawPostlist" ],
        [ "RawSearcher", "classnetspeak_1_1invertedindex_1_1RawSearcher.html", "classnetspeak_1_1invertedindex_1_1RawSearcher" ],
        [ "Record", "classnetspeak_1_1invertedindex_1_1Record.html", "classnetspeak_1_1invertedindex_1_1Record" ],
        [ "RecordReader", "classnetspeak_1_1invertedindex_1_1RecordReader.html", "classnetspeak_1_1invertedindex_1_1RecordReader" ],
        [ "Searcher", "classnetspeak_1_1invertedindex_1_1Searcher.html", "classnetspeak_1_1invertedindex_1_1Searcher" ],
        [ "SortedInput", "classnetspeak_1_1invertedindex_1_1SortedInput.html", "classnetspeak_1_1invertedindex_1_1SortedInput" ],
        [ "StorageReader", "classnetspeak_1_1invertedindex_1_1StorageReader.html", "classnetspeak_1_1invertedindex_1_1StorageReader" ],
        [ "StorageWriter", "classnetspeak_1_1invertedindex_1_1StorageWriter.html", "classnetspeak_1_1invertedindex_1_1StorageWriter" ],
        [ "UnsortedInput", "classnetspeak_1_1invertedindex_1_1UnsortedInput.html", "classnetspeak_1_1invertedindex_1_1UnsortedInput" ]
      ] ],
      [ "model", null, [
        [ "LengthRange", "structnetspeak_1_1model_1_1LengthRange.html", "structnetspeak_1_1model_1_1LengthRange" ],
        [ "NormQueryUnit__", "classnetspeak_1_1model_1_1NormQueryUnit____.html", "classnetspeak_1_1model_1_1NormQueryUnit____" ],
        [ "NormQuery", "classnetspeak_1_1model_1_1NormQuery.html", "classnetspeak_1_1model_1_1NormQuery" ],
        [ "PhraseId__", "structnetspeak_1_1model_1_1PhraseId____.html", "structnetspeak_1_1model_1_1PhraseId____" ],
        [ "Phrase", "classnetspeak_1_1model_1_1Phrase.html", "classnetspeak_1_1model_1_1Phrase" ],
        [ "QueryUnit__", "classnetspeak_1_1model_1_1QueryUnit____.html", "classnetspeak_1_1model_1_1QueryUnit____" ],
        [ "Query", "classnetspeak_1_1model_1_1Query.html", "classnetspeak_1_1model_1_1Query" ],
        [ "QuerySyntax", "structnetspeak_1_1model_1_1QuerySyntax.html", "structnetspeak_1_1model_1_1QuerySyntax" ],
        [ "RawPhraseResult", "classnetspeak_1_1model_1_1RawPhraseResult.html", "classnetspeak_1_1model_1_1RawPhraseResult" ],
        [ "RawRefResult", "classnetspeak_1_1model_1_1RawRefResult.html", "classnetspeak_1_1model_1_1RawRefResult" ],
        [ "RawResult", "classnetspeak_1_1model_1_1RawResult.html", "classnetspeak_1_1model_1_1RawResult" ],
        [ "SearchOptions", "structnetspeak_1_1model_1_1SearchOptions.html", "structnetspeak_1_1model_1_1SearchOptions" ],
        [ "SearchResult", "classnetspeak_1_1model_1_1SearchResult.html", "classnetspeak_1_1model_1_1SearchResult" ],
        [ "SimpleQueryUnit__", "classnetspeak_1_1model_1_1SimpleQueryUnit____.html", "classnetspeak_1_1model_1_1SimpleQueryUnit____" ],
        [ "SimpleQuery", "classnetspeak_1_1model_1_1SimpleQuery.html", "classnetspeak_1_1model_1_1SimpleQuery" ],
        [ "Words", "classnetspeak_1_1model_1_1Words.html", "classnetspeak_1_1model_1_1Words" ]
      ] ],
      [ "regex", null, [
        [ "DefaultRegexIndex", "classnetspeak_1_1regex_1_1DefaultRegexIndex.html", "classnetspeak_1_1regex_1_1DefaultRegexIndex" ],
        [ "RegexIndex", "classnetspeak_1_1regex_1_1RegexIndex.html", "classnetspeak_1_1regex_1_1RegexIndex" ],
        [ "RegexUnit", "structnetspeak_1_1regex_1_1RegexUnit.html", "structnetspeak_1_1regex_1_1RegexUnit" ],
        [ "RegexQuery", "classnetspeak_1_1regex_1_1RegexQuery.html", "classnetspeak_1_1regex_1_1RegexQuery" ],
        [ "RegexQueryBuilder", "classnetspeak_1_1regex_1_1RegexQueryBuilder.html", "classnetspeak_1_1regex_1_1RegexQueryBuilder" ]
      ] ],
      [ "service", null, [
        [ "LoadBalanceProxy", "classnetspeak_1_1service_1_1LoadBalanceProxy.html", "classnetspeak_1_1service_1_1LoadBalanceProxy" ],
        [ "RequestLogger", "classnetspeak_1_1service_1_1RequestLogger.html", "classnetspeak_1_1service_1_1RequestLogger" ],
        [ "UniqueMap", "classnetspeak_1_1service_1_1UniqueMap.html", "classnetspeak_1_1service_1_1UniqueMap" ]
      ] ],
      [ "util", "namespacenetspeak_1_1util.html", [
        [ "ChainCutter", "classnetspeak_1_1util_1_1ChainCutter.html", "classnetspeak_1_1util_1_1ChainCutter" ],
        [ "Config", "classnetspeak_1_1util_1_1Config.html", "classnetspeak_1_1util_1_1Config" ],
        [ "FileDescriptor", "structnetspeak_1_1util_1_1FileDescriptor.html", "structnetspeak_1_1util_1_1FileDescriptor" ],
        [ "JsonWriter", "classnetspeak_1_1util_1_1JsonWriter.html", "classnetspeak_1_1util_1_1JsonWriter" ],
        [ "LfuCache", "classnetspeak_1_1util_1_1LfuCache.html", "classnetspeak_1_1util_1_1LfuCache" ],
        [ "Lockable", "classnetspeak_1_1util_1_1Lockable.html", "classnetspeak_1_1util_1_1Lockable" ],
        [ "format_properties_error", "structnetspeak_1_1util_1_1format__properties__error.html", "structnetspeak_1_1util_1_1format__properties__error" ],
        [ "StringIdMap", "classnetspeak_1_1util_1_1StringIdMap.html", "classnetspeak_1_1util_1_1StringIdMap" ],
        [ "tracable_logic_error", "structnetspeak_1_1util_1_1tracable__logic__error.html", "structnetspeak_1_1util_1_1tracable__logic__error" ],
        [ "tracable_runtime_error", "structnetspeak_1_1util_1_1tracable__runtime__error.html", "structnetspeak_1_1util_1_1tracable__runtime__error" ]
      ] ],
      [ "value", null, [
        [ "big_string", "structnetspeak_1_1value_1_1big__string.html", "structnetspeak_1_1value_1_1big__string" ],
        [ "NameOf< big_string >", "structnetspeak_1_1value_1_1NameOf_3_01big__string_01_4.html", "structnetspeak_1_1value_1_1NameOf_3_01big__string_01_4" ],
        [ "value_traits< big_string >", "structnetspeak_1_1value_1_1value__traits_3_01big__string_01_4.html", "structnetspeak_1_1value_1_1value__traits_3_01big__string_01_4" ],
        [ "generator< big_string >", "structnetspeak_1_1value_1_1generator_3_01big__string_01_4.html", "structnetspeak_1_1value_1_1generator_3_01big__string_01_4" ],
        [ "pair", "classnetspeak_1_1value_1_1pair.html", "classnetspeak_1_1value_1_1pair" ],
        [ "value_traits< pair< T1, T2 > >", "structnetspeak_1_1value_1_1value__traits_3_01pair_3_01T1_00_01T2_01_4_01_4.html", "structnetspeak_1_1value_1_1value__traits_3_01pair_3_01T1_00_01T2_01_4_01_4" ],
        [ "generator< pair< T1, T2 > >", "structnetspeak_1_1value_1_1generator_3_01pair_3_01T1_00_01T2_01_4_01_4.html", "structnetspeak_1_1value_1_1generator_3_01pair_3_01T1_00_01T2_01_4_01_4" ],
        [ "quadruple", "classnetspeak_1_1value_1_1quadruple.html", "classnetspeak_1_1value_1_1quadruple" ],
        [ "value_traits< quadruple< T1, T2, T3, T4 > >", "structnetspeak_1_1value_1_1value__traits_3_01quadruple_3_01T1_00_01T2_00_01T3_00_01T4_01_4_01_4.html", "structnetspeak_1_1value_1_1value__traits_3_01quadruple_3_01T1_00_01T2_00_01T3_00_01T4_01_4_01_4" ],
        [ "generator< quadruple< T1, T2, T3, T4 > >", "structnetspeak_1_1value_1_1generator_3_01quadruple_3_01T1_00_01T2_00_01T3_00_01T4_01_4_01_4.html", "structnetspeak_1_1value_1_1generator_3_01quadruple_3_01T1_00_01T2_00_01T3_00_01T4_01_4_01_4" ],
        [ "NameOf< std::string >", "structnetspeak_1_1value_1_1NameOf_3_01std_1_1string_01_4.html", "structnetspeak_1_1value_1_1NameOf_3_01std_1_1string_01_4" ],
        [ "value_traits< std::string >", "structnetspeak_1_1value_1_1value__traits_3_01std_1_1string_01_4.html", "structnetspeak_1_1value_1_1value__traits_3_01std_1_1string_01_4" ],
        [ "generator< std::string >", "structnetspeak_1_1value_1_1generator_3_01std_1_1string_01_4.html", "structnetspeak_1_1value_1_1generator_3_01std_1_1string_01_4" ],
        [ "triple", "classnetspeak_1_1value_1_1triple.html", "classnetspeak_1_1value_1_1triple" ],
        [ "value_traits< triple< T1, T2, T3 > >", "structnetspeak_1_1value_1_1value__traits_3_01triple_3_01T1_00_01T2_00_01T3_01_4_01_4.html", "structnetspeak_1_1value_1_1value__traits_3_01triple_3_01T1_00_01T2_00_01T3_01_4_01_4" ],
        [ "generator< triple< T1, T2, T3 > >", "structnetspeak_1_1value_1_1generator_3_01triple_3_01T1_00_01T2_00_01T3_01_4_01_4.html", "structnetspeak_1_1value_1_1generator_3_01triple_3_01T1_00_01T2_00_01T3_01_4_01_4" ],
        [ "NameOf", "structnetspeak_1_1value_1_1NameOf.html", null ],
        [ "NameOf< int8_t >", "structnetspeak_1_1value_1_1NameOf_3_01int8__t_01_4.html", "structnetspeak_1_1value_1_1NameOf_3_01int8__t_01_4" ],
        [ "NameOf< uint8_t >", "structnetspeak_1_1value_1_1NameOf_3_01uint8__t_01_4.html", "structnetspeak_1_1value_1_1NameOf_3_01uint8__t_01_4" ],
        [ "NameOf< int16_t >", "structnetspeak_1_1value_1_1NameOf_3_01int16__t_01_4.html", "structnetspeak_1_1value_1_1NameOf_3_01int16__t_01_4" ],
        [ "NameOf< uint16_t >", "structnetspeak_1_1value_1_1NameOf_3_01uint16__t_01_4.html", "structnetspeak_1_1value_1_1NameOf_3_01uint16__t_01_4" ],
        [ "NameOf< int32_t >", "structnetspeak_1_1value_1_1NameOf_3_01int32__t_01_4.html", "structnetspeak_1_1value_1_1NameOf_3_01int32__t_01_4" ],
        [ "NameOf< uint32_t >", "structnetspeak_1_1value_1_1NameOf_3_01uint32__t_01_4.html", "structnetspeak_1_1value_1_1NameOf_3_01uint32__t_01_4" ],
        [ "NameOf< int64_t >", "structnetspeak_1_1value_1_1NameOf_3_01int64__t_01_4.html", "structnetspeak_1_1value_1_1NameOf_3_01int64__t_01_4" ],
        [ "NameOf< uint64_t >", "structnetspeak_1_1value_1_1NameOf_3_01uint64__t_01_4.html", "structnetspeak_1_1value_1_1NameOf_3_01uint64__t_01_4" ],
        [ "NameOf< float >", "structnetspeak_1_1value_1_1NameOf_3_01float_01_4.html", "structnetspeak_1_1value_1_1NameOf_3_01float_01_4" ],
        [ "NameOf< double >", "structnetspeak_1_1value_1_1NameOf_3_01double_01_4.html", "structnetspeak_1_1value_1_1NameOf_3_01double_01_4" ],
        [ "value_traits", "structnetspeak_1_1value_1_1value__traits.html", "structnetspeak_1_1value_1_1value__traits" ],
        [ "generator", "structnetspeak_1_1value_1_1generator.html", "structnetspeak_1_1value_1_1generator" ]
      ] ],
      [ "Configuration", "classnetspeak_1_1Configuration.html", "classnetspeak_1_1Configuration" ],
      [ "Dictionaries", "classnetspeak_1_1Dictionaries.html", "classnetspeak_1_1Dictionaries" ],
      [ "invalid_query_error", "structnetspeak_1_1invalid__query__error.html", "structnetspeak_1_1invalid__query__error" ],
      [ "query_error_message", "structnetspeak_1_1query__error__message.html", "structnetspeak_1_1query__error__message" ],
      [ "error_message", "structnetspeak_1_1error__message.html", "structnetspeak_1_1error__message" ],
      [ "Netspeak", "classnetspeak_1_1Netspeak.html", "classnetspeak_1_1Netspeak" ],
      [ "PhraseCorpus", "classnetspeak_1_1PhraseCorpus.html", "classnetspeak_1_1PhraseCorpus" ],
      [ "PhraseFileParserItem", "structnetspeak_1_1PhraseFileParserItem.html", "structnetspeak_1_1PhraseFileParserItem" ],
      [ "PhraseFileParser", "classnetspeak_1_1PhraseFileParser.html", "classnetspeak_1_1PhraseFileParser" ],
      [ "PhraseFileReader", "classnetspeak_1_1PhraseFileReader.html", "classnetspeak_1_1PhraseFileReader" ],
      [ "Properties", "classnetspeak_1_1Properties.html", "classnetspeak_1_1Properties" ],
      [ "QueryNormalizer", "classnetspeak_1_1QueryNormalizer.html", "classnetspeak_1_1QueryNormalizer" ],
      [ "QueryProcessor", "classnetspeak_1_1QueryProcessor.html", "classnetspeak_1_1QueryProcessor" ],
      [ "index_entry_traits", "structnetspeak_1_1index__entry__traits.html", "structnetspeak_1_1index__entry__traits" ],
      [ "stats_type", "structnetspeak_1_1stats__type.html", "structnetspeak_1_1stats__type" ],
      [ "RetrievalStrategy", "classnetspeak_1_1RetrievalStrategy.html", "classnetspeak_1_1RetrievalStrategy" ],
      [ "RetrievalStrategy3Tag", "structnetspeak_1_1RetrievalStrategy3Tag.html", "structnetspeak_1_1RetrievalStrategy3Tag" ],
      [ "index_entry_traits< RetrievalStrategy3Tag >", "structnetspeak_1_1index__entry__traits_3_01RetrievalStrategy3Tag_01_4.html", "structnetspeak_1_1index__entry__traits_3_01RetrievalStrategy3Tag_01_4" ],
      [ "RetrievalStrategy< RetrievalStrategy3Tag >", "classnetspeak_1_1RetrievalStrategy_3_01RetrievalStrategy3Tag_01_4.html", "classnetspeak_1_1RetrievalStrategy_3_01RetrievalStrategy3Tag_01_4" ]
    ] ]
];