var searchData=
[
  ['rawindexer_154',['RawIndexer',['../classnetspeak_1_1invertedindex_1_1RawIndexer.html',1,'netspeak::invertedindex']]],
  ['rawphraseresult_155',['RawPhraseResult',['../classnetspeak_1_1model_1_1RawPhraseResult.html',1,'netspeak::model']]],
  ['rawpostlist_156',['RawPostlist',['../classnetspeak_1_1invertedindex_1_1RawPostlist.html',1,'netspeak::invertedindex']]],
  ['rawrefresult_157',['RawRefResult',['../classnetspeak_1_1model_1_1RawRefResult.html',1,'netspeak::model']]],
  ['rawresult_158',['RawResult',['../classnetspeak_1_1model_1_1RawResult.html',1,'netspeak::model']]],
  ['rawsearcher_159',['RawSearcher',['../classnetspeak_1_1invertedindex_1_1RawSearcher.html',1,'netspeak::invertedindex']]],
  ['readme_160',['README',['../md_netspeak_model_README.html',1,'(Global Namespace)'],['../md_netspeak_regex_README.html',1,'(Global Namespace)'],['../md_netspeak_util_README.html',1,'(Global Namespace)']]],
  ['readpostlist_161',['ReadPostlist',['../classnetspeak_1_1invertedindex_1_1StorageReader.html#abcce642b9fe62e0c255d1bb1360084c5',1,'netspeak::invertedindex::StorageReader']]],
  ['record_162',['Record',['../classnetspeak_1_1invertedindex_1_1Record.html',1,'netspeak::invertedindex']]],
  ['recordreader_163',['RecordReader',['../classnetspeak_1_1invertedindex_1_1RecordReader.html',1,'netspeak::invertedindex']]],
  ['recordreader_3c_20model_3a_3aphraseindexvalue_20_3e_164',['RecordReader&lt; model::PhraseIndexValue &gt;',['../classnetspeak_1_1invertedindex_1_1RecordReader.html',1,'netspeak::invertedindex']]],
  ['ref_165',['Ref',['../classnetspeak_1_1model_1_1RawRefResult_1_1Ref.html',1,'netspeak::model::RawRefResult']]],
  ['refitem_166',['RefItem',['../structnetspeak_1_1model_1_1RawResult_1_1RefItem.html',1,'netspeak::model::RawResult']]],
  ['refs_167',['refs',['../classnetspeak_1_1model_1_1RawRefResult.html#ab4b1c64910f6dec3c6a069b50fb8374c',1,'netspeak::model::RawRefResult::refs()'],['../classnetspeak_1_1model_1_1RawResult.html#a897c491fd745fade2acdc7a3b71977dc',1,'netspeak::model::RawResult::refs()']]],
  ['regexcommand_168',['RegexCommand',['../classcli_1_1RegexCommand.html',1,'cli']]],
  ['regexindex_169',['RegexIndex',['../classnetspeak_1_1regex_1_1RegexIndex.html',1,'netspeak::regex']]],
  ['regexquery_170',['RegexQuery',['../classnetspeak_1_1regex_1_1RegexQuery.html',1,'netspeak::regex']]],
  ['regexquerybuilder_171',['RegexQueryBuilder',['../classnetspeak_1_1regex_1_1RegexQueryBuilder.html',1,'netspeak::regex']]],
  ['regexunit_172',['RegexUnit',['../structnetspeak_1_1regex_1_1RegexUnit.html',1,'netspeak::regex']]],
  ['reject_5fall_173',['reject_all',['../classnetspeak_1_1regex_1_1RegexQuery.html#a2f4d2e52bef616730e1395063c3e82ed',1,'netspeak::regex::RegexQuery']]],
  ['requestlogger_174',['RequestLogger',['../classnetspeak_1_1service_1_1RequestLogger.html',1,'netspeak::service']]],
  ['resize_175',['resize',['../classnetspeak_1_1invertedindex_1_1ByteBuffer.html#ab83184815805ed4606aa924eb9a6f42c',1,'netspeak::invertedindex::ByteBuffer']]],
  ['result_5fcache_5fitem_176',['result_cache_item',['../structnetspeak_1_1Netspeak_1_1result__cache__item.html',1,'netspeak::Netspeak']]],
  ['retrievalstrategy_177',['RetrievalStrategy',['../classnetspeak_1_1RetrievalStrategy.html',1,'netspeak']]],
  ['retrievalstrategy3tag_178',['RetrievalStrategy3Tag',['../structnetspeak_1_1RetrievalStrategy3Tag.html',1,'netspeak']]],
  ['retrievalstrategy_3c_20netspeak_3a_3aretrievalstrategy3tag_20_3e_179',['RetrievalStrategy&lt; netspeak::RetrievalStrategy3Tag &gt;',['../classnetspeak_1_1RetrievalStrategy.html',1,'netspeak']]],
  ['retrievalstrategy_3c_20retrievalstrategy3tag_20_3e_180',['RetrievalStrategy&lt; RetrievalStrategy3Tag &gt;',['../classnetspeak_1_1RetrievalStrategy_3_01RetrievalStrategy3Tag_01_4.html',1,'netspeak']]]
];
