var searchData=
[
  ['search_5fconfig_175',['search_config',['../structnetspeak_1_1Netspeak_1_1search__config.html',1,'netspeak::Netspeak']]],
  ['search_5fpostlist_176',['search_postlist',['../classnetspeak_1_1invertedindex_1_1Searcher.html#a22173e45e7e5108548efba4f7f51960a',1,'netspeak::invertedindex::Searcher']]],
  ['searcher_177',['Searcher',['../classnetspeak_1_1invertedindex_1_1Searcher.html',1,'netspeak::invertedindex']]],
  ['searcher_3c_20netspeak_3a_3avalue_3a_3apair_20_3e_178',['Searcher&lt; netspeak::value::pair &gt;',['../classnetspeak_1_1invertedindex_1_1Searcher.html',1,'netspeak::invertedindex']]],
  ['searchoptions_179',['SearchOptions',['../structnetspeak_1_1model_1_1SearchOptions.html',1,'netspeak::model']]],
  ['searchresult_180',['SearchResult',['../classnetspeak_1_1model_1_1SearchResult.html',1,'netspeak::model']]],
  ['segments_181',['segments',['../classnetspeak_1_1util_1_1ChainCutter.html#a1a87aa388ec11002b0da2ecdb647eebc',1,'netspeak::util::ChainCutter']]],
  ['servecommand_182',['ServeCommand',['../classcli_1_1ServeCommand.html',1,'cli']]],
  ['shellcommand_183',['ShellCommand',['../classcli_1_1ShellCommand.html',1,'cli']]],
  ['simplequery_184',['SimpleQuery',['../classnetspeak_1_1model_1_1SimpleQuery.html',1,'netspeak::model']]],
  ['simplequeryunit_5f_5f_185',['SimpleQueryUnit__',['../classnetspeak_1_1model_1_1SimpleQueryUnit____.html',1,'netspeak::model']]],
  ['size_186',['size',['../classnetspeak_1_1util_1_1ChainCutter.html#a326a100a5403dc100a506bb7e219e6a5',1,'netspeak::util::ChainCutter::size()'],['../classnetspeak_1_1invertedindex_1_1ByteBuffer.html#ac7160f8bd36f86815662909c0722556f',1,'netspeak::invertedindex::ByteBuffer::size()']]],
  ['sortedinput_187',['SortedInput',['../classnetspeak_1_1invertedindex_1_1SortedInput.html',1,'netspeak::invertedindex']]],
  ['source_188',['Source',['../structnetspeak_1_1model_1_1NormQueryUnit_____1_1Source.html',1,'netspeak::model::NormQueryUnit__']]],
  ['specification_189',['Specification',['../specification.html',1,'DeveloperIdx']]],
  ['stats_5ftype_190',['stats_type',['../structnetspeak_1_1invertedindex_1_1IndexStrategy_1_1stats__type.html',1,'netspeak::invertedindex::IndexStrategy&lt; T &gt;::stats_type'],['../structnetspeak_1_1stats__type.html',1,'netspeak::stats_type']]],
  ['storagereader_191',['StorageReader',['../classnetspeak_1_1invertedindex_1_1StorageReader.html',1,'netspeak::invertedindex']]],
  ['storagereader_3c_20value_2c_20true_20_3e_192',['StorageReader&lt; Value, true &gt;',['../classnetspeak_1_1invertedindex_1_1StorageReader.html',1,'netspeak::invertedindex']]],
  ['storagewriter_193',['StorageWriter',['../classnetspeak_1_1invertedindex_1_1StorageWriter.html',1,'netspeak::invertedindex']]],
  ['storagewriter_3c_20value_5ftype_20_3e_194',['StorageWriter&lt; value_type &gt;',['../classnetspeak_1_1invertedindex_1_1StorageWriter.html',1,'netspeak::invertedindex']]],
  ['stresscommand_195',['StressCommand',['../classcli_1_1StressCommand.html',1,'cli']]],
  ['string_5fentry_196',['string_entry',['../structnetspeak_1_1util_1_1StringIdMap_1_1string__entry.html',1,'netspeak::util::StringIdMap']]],
  ['string_5fstream_5fwrapper_197',['string_stream_wrapper',['../structnetspeak_1_1util_1_1JsonWriter_1_1string__stream__wrapper.html',1,'netspeak::util::JsonWriter']]],
  ['stringidmap_198',['StringIdMap',['../classnetspeak_1_1util_1_1StringIdMap.html',1,'netspeak::util']]],
  ['swap_5ftype_199',['swap_type',['../structnetspeak_1_1invertedindex_1_1swap__type.html',1,'netspeak::invertedindex']]],
  ['syntaxerror_200',['syntaxError',['../classantlr4_1_1QueryErrorHandler.html#a4a9a7b03391b90b71833ea399575716e',1,'antlr4::QueryErrorHandler']]]
];
