var searchData=
[
  ['rawindexer_330',['RawIndexer',['../classnetspeak_1_1invertedindex_1_1RawIndexer.html',1,'netspeak::invertedindex']]],
  ['rawphraseresult_331',['RawPhraseResult',['../classnetspeak_1_1model_1_1RawPhraseResult.html',1,'netspeak::model']]],
  ['rawpostlist_332',['RawPostlist',['../classnetspeak_1_1invertedindex_1_1RawPostlist.html',1,'netspeak::invertedindex']]],
  ['rawrefresult_333',['RawRefResult',['../classnetspeak_1_1model_1_1RawRefResult.html',1,'netspeak::model']]],
  ['rawresult_334',['RawResult',['../classnetspeak_1_1model_1_1RawResult.html',1,'netspeak::model']]],
  ['rawsearcher_335',['RawSearcher',['../classnetspeak_1_1invertedindex_1_1RawSearcher.html',1,'netspeak::invertedindex']]],
  ['record_336',['Record',['../classnetspeak_1_1invertedindex_1_1Record.html',1,'netspeak::invertedindex']]],
  ['recordreader_337',['RecordReader',['../classnetspeak_1_1invertedindex_1_1RecordReader.html',1,'netspeak::invertedindex']]],
  ['recordreader_3c_20model_3a_3aphraseindexvalue_20_3e_338',['RecordReader&lt; model::PhraseIndexValue &gt;',['../classnetspeak_1_1invertedindex_1_1RecordReader.html',1,'netspeak::invertedindex']]],
  ['ref_339',['Ref',['../classnetspeak_1_1model_1_1RawRefResult_1_1Ref.html',1,'netspeak::model::RawRefResult']]],
  ['refitem_340',['RefItem',['../structnetspeak_1_1model_1_1RawResult_1_1RefItem.html',1,'netspeak::model::RawResult']]],
  ['regexcommand_341',['RegexCommand',['../classcli_1_1RegexCommand.html',1,'cli']]],
  ['regexindex_342',['RegexIndex',['../classnetspeak_1_1regex_1_1RegexIndex.html',1,'netspeak::regex']]],
  ['regexquery_343',['RegexQuery',['../classnetspeak_1_1regex_1_1RegexQuery.html',1,'netspeak::regex']]],
  ['regexquerybuilder_344',['RegexQueryBuilder',['../classnetspeak_1_1regex_1_1RegexQueryBuilder.html',1,'netspeak::regex']]],
  ['regexunit_345',['RegexUnit',['../structnetspeak_1_1regex_1_1RegexUnit.html',1,'netspeak::regex']]],
  ['requestlogger_346',['RequestLogger',['../classnetspeak_1_1service_1_1RequestLogger.html',1,'netspeak::service']]],
  ['result_5fcache_5fitem_347',['result_cache_item',['../structnetspeak_1_1Netspeak_1_1result__cache__item.html',1,'netspeak::Netspeak']]],
  ['retrievalstrategy_348',['RetrievalStrategy',['../classnetspeak_1_1RetrievalStrategy.html',1,'netspeak']]],
  ['retrievalstrategy3tag_349',['RetrievalStrategy3Tag',['../structnetspeak_1_1RetrievalStrategy3Tag.html',1,'netspeak']]],
  ['retrievalstrategy_3c_20netspeak_3a_3aretrievalstrategy3tag_20_3e_350',['RetrievalStrategy&lt; netspeak::RetrievalStrategy3Tag &gt;',['../classnetspeak_1_1RetrievalStrategy.html',1,'netspeak']]],
  ['retrievalstrategy_3c_20retrievalstrategy3tag_20_3e_351',['RetrievalStrategy&lt; RetrievalStrategy3Tag &gt;',['../classnetspeak_1_1RetrievalStrategy_3_01RetrievalStrategy3Tag_01_4.html',1,'netspeak']]]
];
