var searchData=
[
  ['rawindexer_331',['RawIndexer',['../classnetspeak_1_1invertedindex_1_1RawIndexer.html',1,'netspeak::invertedindex']]],
  ['rawphraseresult_332',['RawPhraseResult',['../classnetspeak_1_1model_1_1RawPhraseResult.html',1,'netspeak::model']]],
  ['rawpostlist_333',['RawPostlist',['../classnetspeak_1_1invertedindex_1_1RawPostlist.html',1,'netspeak::invertedindex']]],
  ['rawrefresult_334',['RawRefResult',['../classnetspeak_1_1model_1_1RawRefResult.html',1,'netspeak::model']]],
  ['rawresult_335',['RawResult',['../classnetspeak_1_1model_1_1RawResult.html',1,'netspeak::model']]],
  ['rawsearcher_336',['RawSearcher',['../classnetspeak_1_1invertedindex_1_1RawSearcher.html',1,'netspeak::invertedindex']]],
  ['record_337',['Record',['../classnetspeak_1_1invertedindex_1_1Record.html',1,'netspeak::invertedindex']]],
  ['recordreader_338',['RecordReader',['../classnetspeak_1_1invertedindex_1_1RecordReader.html',1,'netspeak::invertedindex']]],
  ['recordreader_3c_20model_3a_3aphraseindexvalue_20_3e_339',['RecordReader&lt; model::PhraseIndexValue &gt;',['../classnetspeak_1_1invertedindex_1_1RecordReader.html',1,'netspeak::invertedindex']]],
  ['ref_340',['Ref',['../classnetspeak_1_1model_1_1RawRefResult_1_1Ref.html',1,'netspeak::model::RawRefResult']]],
  ['refitem_341',['RefItem',['../structnetspeak_1_1model_1_1RawResult_1_1RefItem.html',1,'netspeak::model::RawResult']]],
  ['regexcommand_342',['RegexCommand',['../classcli_1_1RegexCommand.html',1,'cli']]],
  ['regexindex_343',['RegexIndex',['../classnetspeak_1_1regex_1_1RegexIndex.html',1,'netspeak::regex']]],
  ['regexquery_344',['RegexQuery',['../classnetspeak_1_1regex_1_1RegexQuery.html',1,'netspeak::regex']]],
  ['regexquerybuilder_345',['RegexQueryBuilder',['../classnetspeak_1_1regex_1_1RegexQueryBuilder.html',1,'netspeak::regex']]],
  ['regexunit_346',['RegexUnit',['../structnetspeak_1_1regex_1_1RegexUnit.html',1,'netspeak::regex']]],
  ['requestlogger_347',['RequestLogger',['../classnetspeak_1_1service_1_1RequestLogger.html',1,'netspeak::service']]],
  ['result_5fcache_5fitem_348',['result_cache_item',['../structnetspeak_1_1Netspeak_1_1result__cache__item.html',1,'netspeak::Netspeak']]],
  ['retrievalstrategy_349',['RetrievalStrategy',['../classnetspeak_1_1RetrievalStrategy.html',1,'netspeak']]],
  ['retrievalstrategy3tag_350',['RetrievalStrategy3Tag',['../structnetspeak_1_1RetrievalStrategy3Tag.html',1,'netspeak']]],
  ['retrievalstrategy_3c_20netspeak_3a_3aretrievalstrategy3tag_20_3e_351',['RetrievalStrategy&lt; netspeak::RetrievalStrategy3Tag &gt;',['../classnetspeak_1_1RetrievalStrategy.html',1,'netspeak']]],
  ['retrievalstrategy_3c_20retrievalstrategy3tag_20_3e_352',['RetrievalStrategy&lt; RetrievalStrategy3Tag &gt;',['../classnetspeak_1_1RetrievalStrategy_3_01RetrievalStrategy3Tag_01_4.html',1,'netspeak']]]
];
