var searchData=
[
  ['rawindexer_332',['RawIndexer',['../classnetspeak_1_1invertedindex_1_1RawIndexer.html',1,'netspeak::invertedindex']]],
  ['rawphraseresult_333',['RawPhraseResult',['../classnetspeak_1_1model_1_1RawPhraseResult.html',1,'netspeak::model']]],
  ['rawpostlist_334',['RawPostlist',['../classnetspeak_1_1invertedindex_1_1RawPostlist.html',1,'netspeak::invertedindex']]],
  ['rawrefresult_335',['RawRefResult',['../classnetspeak_1_1model_1_1RawRefResult.html',1,'netspeak::model']]],
  ['rawresult_336',['RawResult',['../classnetspeak_1_1model_1_1RawResult.html',1,'netspeak::model']]],
  ['rawsearcher_337',['RawSearcher',['../classnetspeak_1_1invertedindex_1_1RawSearcher.html',1,'netspeak::invertedindex']]],
  ['record_338',['Record',['../classnetspeak_1_1invertedindex_1_1Record.html',1,'netspeak::invertedindex']]],
  ['recordreader_339',['RecordReader',['../classnetspeak_1_1invertedindex_1_1RecordReader.html',1,'netspeak::invertedindex']]],
  ['recordreader_3c_20model_3a_3aphraseindexvalue_20_3e_340',['RecordReader&lt; model::PhraseIndexValue &gt;',['../classnetspeak_1_1invertedindex_1_1RecordReader.html',1,'netspeak::invertedindex']]],
  ['ref_341',['Ref',['../classnetspeak_1_1model_1_1RawRefResult_1_1Ref.html',1,'netspeak::model::RawRefResult']]],
  ['refitem_342',['RefItem',['../structnetspeak_1_1model_1_1RawResult_1_1RefItem.html',1,'netspeak::model::RawResult']]],
  ['regexcommand_343',['RegexCommand',['../classcli_1_1RegexCommand.html',1,'cli']]],
  ['regexindex_344',['RegexIndex',['../classnetspeak_1_1regex_1_1RegexIndex.html',1,'netspeak::regex']]],
  ['regexquery_345',['RegexQuery',['../classnetspeak_1_1regex_1_1RegexQuery.html',1,'netspeak::regex']]],
  ['regexquerybuilder_346',['RegexQueryBuilder',['../classnetspeak_1_1regex_1_1RegexQueryBuilder.html',1,'netspeak::regex']]],
  ['regexunit_347',['RegexUnit',['../structnetspeak_1_1regex_1_1RegexUnit.html',1,'netspeak::regex']]],
  ['requestlogger_348',['RequestLogger',['../classnetspeak_1_1service_1_1RequestLogger.html',1,'netspeak::service']]],
  ['result_5fcache_5fitem_349',['result_cache_item',['../structnetspeak_1_1Netspeak_1_1result__cache__item.html',1,'netspeak::Netspeak']]],
  ['retrievalstrategy_350',['RetrievalStrategy',['../classnetspeak_1_1RetrievalStrategy.html',1,'netspeak']]],
  ['retrievalstrategy3tag_351',['RetrievalStrategy3Tag',['../structnetspeak_1_1RetrievalStrategy3Tag.html',1,'netspeak']]],
  ['retrievalstrategy_3c_20netspeak_3a_3aretrievalstrategy3tag_20_3e_352',['RetrievalStrategy&lt; netspeak::RetrievalStrategy3Tag &gt;',['../classnetspeak_1_1RetrievalStrategy.html',1,'netspeak']]],
  ['retrievalstrategy_3c_20retrievalstrategy3tag_20_3e_353',['RetrievalStrategy&lt; RetrievalStrategy3Tag &gt;',['../classnetspeak_1_1RetrievalStrategy_3_01RetrievalStrategy3Tag_01_4.html',1,'netspeak']]]
];
