var searchData=
[
  ['search_5fconfig_0',['search_config',['../structnetspeak_1_1Netspeak_1_1search__config.html',1,'netspeak::Netspeak']]],
  ['searcher_1',['Searcher',['../classnetspeak_1_1invertedindex_1_1Searcher.html',1,'netspeak::invertedindex']]],
  ['searcher_3c_20netspeak_3a_3avalue_3a_3apair_20_3e_2',['Searcher&lt; netspeak::value::pair &gt;',['../classnetspeak_1_1invertedindex_1_1Searcher.html',1,'netspeak::invertedindex']]],
  ['searchoptions_3',['SearchOptions',['../structnetspeak_1_1model_1_1SearchOptions.html',1,'netspeak::model']]],
  ['searchresult_4',['SearchResult',['../classnetspeak_1_1model_1_1SearchResult.html',1,'netspeak::model']]],
  ['servecommand_5',['ServeCommand',['../classcli_1_1ServeCommand.html',1,'cli']]],
  ['shellcommand_6',['ShellCommand',['../classcli_1_1ShellCommand.html',1,'cli']]],
  ['simplequery_7',['SimpleQuery',['../classnetspeak_1_1model_1_1SimpleQuery.html',1,'netspeak::model']]],
  ['simplequerynormalizer_8',['SimpleQueryNormalizer',['../classnetspeak_1_1SimpleQueryNormalizer.html',1,'netspeak']]],
  ['simplequeryoptimizer_9',['SimpleQueryOptimizer',['../classnetspeak_1_1SimpleQueryOptimizer.html',1,'netspeak']]],
  ['simplequeryunit_5f_5f_10',['SimpleQueryUnit__',['../classnetspeak_1_1model_1_1SimpleQueryUnit____.html',1,'netspeak::model']]],
  ['sortedinput_11',['SortedInput',['../classnetspeak_1_1invertedindex_1_1SortedInput.html',1,'netspeak::invertedindex']]],
  ['source_12',['Source',['../structnetspeak_1_1model_1_1NormQueryUnit_____1_1Source.html',1,'netspeak::model::NormQueryUnit__']]],
  ['starquery_13',['StarQuery',['../classnetspeak_1_1StarQuery.html',1,'netspeak']]],
  ['starqueryconverter_14',['StarQueryConverter',['../classnetspeak_1_1StarQueryConverter.html',1,'netspeak']]],
  ['stats_5ftype_15',['stats_type',['../structnetspeak_1_1invertedindex_1_1IndexStrategy_1_1stats__type.html',1,'netspeak::invertedindex::IndexStrategy&lt; T &gt;::stats_type'],['../structnetspeak_1_1stats__type.html',1,'netspeak::stats_type']]],
  ['storagereader_16',['StorageReader',['../classnetspeak_1_1invertedindex_1_1StorageReader.html',1,'netspeak::invertedindex']]],
  ['storagereader_3c_20netspeak_3a_3avalue_3a_3apair_2c_20true_20_3e_17',['StorageReader&lt; netspeak::value::pair, true &gt;',['../classnetspeak_1_1invertedindex_1_1StorageReader.html',1,'netspeak::invertedindex']]],
  ['storagereader_3c_20value_2c_20true_20_3e_18',['StorageReader&lt; Value, true &gt;',['../classnetspeak_1_1invertedindex_1_1StorageReader.html',1,'netspeak::invertedindex']]],
  ['storagewriter_19',['StorageWriter',['../classnetspeak_1_1invertedindex_1_1StorageWriter.html',1,'netspeak::invertedindex']]],
  ['storagewriter_3c_20value_5ftype_20_3e_20',['StorageWriter&lt; value_type &gt;',['../classnetspeak_1_1invertedindex_1_1StorageWriter.html',1,'netspeak::invertedindex']]],
  ['stresscommand_21',['StressCommand',['../classcli_1_1StressCommand.html',1,'cli']]],
  ['string_5fentry_22',['string_entry',['../structnetspeak_1_1util_1_1StringIdMap_1_1string__entry.html',1,'netspeak::util::StringIdMap']]],
  ['string_5fstream_5fwrapper_23',['string_stream_wrapper',['../structnetspeak_1_1util_1_1JsonWriter_1_1string__stream__wrapper.html',1,'netspeak::util::JsonWriter']]],
  ['stringidmap_24',['StringIdMap',['../classnetspeak_1_1util_1_1StringIdMap.html',1,'netspeak::util']]],
  ['swap_5ftype_25',['swap_type',['../structnetspeak_1_1invertedindex_1_1swap__type.html',1,'netspeak::invertedindex']]]
];
