
name: C++ make build and test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: sudo ./build/install-dependencies.sh
    - name: Build
      run: qmake && make
    - name: Run tests
      run: ./build/run-tests.sh
