
name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    container: webis/netspeak-env:0.1

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: bash ./build/install-dependencies.sh
    - run: bash ./build/cmake.sh
    - name: Build
      run: make
    - name: Run tests
      run: ./build/run-tests.sh
